version = 0.1

[default.deploy.parameters]
stack_name = "secret-oracle-backend"
resolve_s3 = true
s3_prefix = "secret-oracle-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "RandomImageApiUrl=\"https://qqgfg03g58.execute-api.us-east-1.amazonaws.com/prod/random-image\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
